# Generated by Django 3.2.5 on 2021-08-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_username_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
    ]
