# Generated by Django 3.2.5 on 2021-08-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210822_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
