# Generated by Django 3.2.5 on 2021-08-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره تماس'),
        ),
    ]
