# Generated by Django 3.2.5 on 2021-09-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210828_1230'),
        ('order', '0003_remove_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.book', verbose_name='محصول'),
        ),
    ]
