# Generated by Django 3.2.5 on 2021-08-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('author', models.CharField(max_length=200, verbose_name='نویسنده کتاب')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('cover', models.ImageField(blank=True, upload_to='cover/products/', verbose_name='کاور')),
                ('available', models.BooleanField(default=True, verbose_name='موجودی انبار')),
                ('created', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت کتاب')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت کتاب')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, verbose_name='اسلاگ')),
                ('c_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='coupons.cashdiscount', verbose_name='تخفیف نقدی')),
                ('category', models.ManyToManyField(related_name='books', to='product.Category', verbose_name='دسته بندی')),
                ('p_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='coupons.percentagediscount', verbose_name='تخفیف درصدی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
                'ordering': ['title'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
