# Generated by Django 3.2.5 on 2021-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_book_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='موجودی انبار '),
        ),
    ]
