# Generated by Django 3.2.5 on 2021-08-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdiscount',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='cashdiscount',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='percentagediscount',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='percentagediscount',
            name='valid_to',
        ),
    ]
